"""add foreign keys

Revision ID: 8311ffbad5dd
Revises: b10bc0c09c62
Create Date: 2025-10-01 14:06:57.858059+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8311ffbad5dd'
down_revision = 'b10bc0c09c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_bridge_status_bridge', 'bridge_status', 'bridges', ['bridge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_incidents_bridge', 'incidents', 'bridges', ['bridge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_subscriptions_user', 'user_subscriptions', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_subscriptions_bridge', 'user_subscriptions', 'bridges', ['bridge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_subscriptions_bridge', 'user_subscriptions', type_='foreignkey')
    op.drop_constraint('fk_user_subscriptions_user', 'user_subscriptions', type_='foreignkey')
    op.drop_constraint('fk_incidents_bridge', 'incidents', type_='foreignkey')
    op.drop_constraint('fk_bridge_status_bridge', 'bridge_status', type_='foreignkey')
    # ### end Alembic commands ###